/**
 * Moteur IA — détection de génération / réécriture sur TEXTE (PDF, DOCX).
 *
 * Même contrat que la détection image : aucune valeur de repli inventée.
 * Une indisponibilité renvoie `trustScore: null` avec un statut explicite.
 */

import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";

import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import type { Anomaly, EvidenceItem } from "./types";
import { aiUnavailable, trustFromSyntheticProbability, type AiOutcome } from "./ai-types";
import { callAiJson } from "./ai-call.server";

const PayloadSchema = z.object({
  text: z.string().min(120).max(24_000),
});

type Classification = "human" | "ai_generated" | "ai_rewritten" | "mixed";

interface AiTextVerdict {
  classification: Classification;
  confidence: number; // 0..1
  indicators: string[];
  reasoning: string;
}

export const detectAiText = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((input: unknown) => PayloadSchema.parse(input))
  .handler(async ({ data }): Promise<AiOutcome> => {
    const call = await callAiJson({
      gatewayModel: "google/gemini-3.6-flash",
      googleModel: "gemini-3.6-flash",
      messages: [
        {
          role: "system",
          content:
            "You are a forensic linguistics expert. Classify the provided document text as one of: " +
            '"human" (written by a human), "ai_generated" (fully generated by a LLM), ' +
            '"ai_rewritten" (originally human but rewritten/polished by a LLM), or "mixed". ' +
            "Reply ONLY with strict JSON matching " +
            '{"classification": "human|ai_generated|ai_rewritten|mixed", "confidence": number 0..1, "indicators": string[], "reasoning": string}. ' +
            "Indicators must reference concrete markers: unnatural homogeneity, low perplexity patterns, " +
            "boilerplate LLM phrases, suspiciously balanced structure, lack of typos/idiolects, " +
            "generic transitions, over-explanation. Be conservative — flag ai_* only above 0.6 confidence.",
        },
        {
          role: "user",
          content: `Analyse linguistique forensic :\n\n"""${data.text.slice(0, 12_000)}"""`,
        },
      ],
    });

    if (!call.ok) return aiUnavailable("text", call.errorCode, call.detail);
    const { content, model } = call;

    let parsed: AiTextVerdict;
    try {
      const obj = JSON.parse(content);
      const cls = obj.classification;
      parsed = {
        classification: (["human", "ai_generated", "ai_rewritten", "mixed"].includes(cls) ? cls : "human") as Classification,
        confidence: Math.max(0, Math.min(1, Number(obj.confidence) || 0)),
        indicators: Array.isArray(obj.indicators) ? obj.indicators.slice(0, 8).map(String) : [],
        reasoning: typeof obj.reasoning === "string" ? obj.reasoning.slice(0, 480) : "",
      };
    } catch {
      return aiUnavailable("text", "PARSE_ERROR", "réponse non conforme au schéma JSON attendu");
    }

    const anomalies: Anomaly[] = [];
    let syntheticProbability: number;
    switch (parsed.classification) {
      case "ai_generated":
        syntheticProbability = Math.round(parsed.confidence * 100);
        break;
      case "ai_rewritten":
        syntheticProbability = Math.round(parsed.confidence * 70);
        break;
      case "mixed":
        syntheticProbability = Math.round(parsed.confidence * 50);
        break;
      default:
        syntheticProbability = Math.round((1 - parsed.confidence) * 30);
        break;
    }

    if (parsed.classification === "ai_generated" && parsed.confidence >= 0.6) {
      anomalies.push({
        engine: "ai",
        code: "AI_TEXT_GENERATED",
        label: `Texte probablement généré par IA (${Math.round(parsed.confidence * 100)} %)`,
        detail: parsed.indicators.length ? "Marqueurs : " + parsed.indicators.join(" · ") : parsed.reasoning,
        severity: parsed.confidence >= 0.85 ? "critical" : "high",
      });
    } else if (parsed.classification === "ai_rewritten" && parsed.confidence >= 0.6) {
      anomalies.push({
        engine: "ai",
        code: "AI_TEXT_REWRITTEN",
        label: `Texte probablement réécrit par IA (${Math.round(parsed.confidence * 100)} %)`,
        detail: parsed.indicators.length ? "Marqueurs : " + parsed.indicators.join(" · ") : parsed.reasoning,
        severity: parsed.confidence >= 0.85 ? "high" : "medium",
      });
    } else if (parsed.classification === "mixed" && parsed.confidence >= 0.6) {
      anomalies.push({
        engine: "ai",
        code: "AI_TEXT_REWRITTEN",
        label: `Texte mixte (humain + IA) — confiance ${Math.round(parsed.confidence * 100)} %`,
        detail: parsed.reasoning,
        severity: "medium",
      });
    }

    const evidence: EvidenceItem[] = [
      { group: "pdf", key: "ai_text_classification", label: "Classification linguistique", value: parsed.classification },
      { group: "pdf", key: "ai_text_synthetic_probability", label: "Probabilité de contenu synthétique (texte)", value: syntheticProbability + " %" },
      { group: "pdf", key: "ai_text_confidence", label: "Confiance du détecteur", value: Math.round(parsed.confidence * 100) + " %" },
      { group: "pdf", key: "ai_text_model", label: "Modèle utilisé", value: model },
    ];
    if (parsed.indicators.length) {
      evidence.push({ group: "pdf", key: "ai_text_indicators", label: "Marqueurs linguistiques", value: parsed.indicators.join(", ") });
    }

    return {
      status: "completed",
      kind: "text",
      syntheticProbability,
      serviceConfidence: Math.round(parsed.confidence * 100),
      trustScore: trustFromSyntheticProbability(syntheticProbability),
      modelVersion: model,
      analyzedAt: new Date().toISOString(),
      rationale: parsed.reasoning || (parsed.classification === "human" ? "Aucun marqueur IA évident" : "Marqueurs IA détectés"),
      errorCode: null,
      anomalies,
      evidence,
    };
  });
